# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# # Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.3.1



jobs:
    install:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - run: time npm ci
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - ./node_modules
    test:
      docker:
        - image: circleci/node:10
      steps:
        - setup_remote_docker
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - checkout
        - run: |
            echo "export DOCKER_IMAGE=eritikass/whatever:cicleci-$CIRCLE_WORKFLOW_ID" >> $BASH_ENV
        - run: echo $DOCKER_IMAGE
        - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
        - run: npm test
        - run: docker build --pull -t $DOCKER_IMAGE .
        - run: docker run --rm $DOCKER_IMAGE npm test
        - run: docker ps
        - run: docker push $DOCKER_IMAGE


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build_and_test:
    jobs:
      - install
      - test