# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1


jobs:
    install:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - run: |
            echo "hello world"
            echo "CIRCLE_SHA1=[$CIRCLE_SHA1]"
            echo "CIRCLE_TAG=[$CIRCLE_TAG]"
            echo "CIRCLE_BRANCH=[$CIRCLE_BRANCH]"

    test:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - run: |
            echo "hello world"
            echo "CIRCLE_SHA1=[$CIRCLE_SHA1]"
            echo "CIRCLE_TAG=[$CIRCLE_TAG]"
            echo "CIRCLE_BRANCH=[$CIRCLE_BRANCH]"

    build:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - run: |
            echo "hello world"
            echo "CIRCLE_SHA1=[$CIRCLE_SHA1]"
            echo "CIRCLE_TAG=[$CIRCLE_TAG]"
            echo "CIRCLE_BRANCH=[$CIRCLE_BRANCH]"


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  testing_things:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - install
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - install
            - test