# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:

  test:
    working_directory: ~/circleci-test
    docker:
      - image: registry.gitlab.com/eritikass/ci-database:t1245
    steps:
      - checkout
      
      - run: aws --version
      - run:
          name: "auth for aws"
          command: |
            aws configure set aws_access_key_id "$AWS_KEY" --profile "default"
            aws configure set aws_secret_access_key "$AWS_SECRET" --profile "default"
            aws configure set region "eu-west-1" --profile "default"

      - run:
          name: "send message"
          command: |
            # hwlo
            aws sns publish --topic-arn=${AWS_SNS_NAME} --message "test:${CIRCLE_WORKFLOW_ID}"

      - run:
          name: "send message"
          command: |
            aws sns publish --topic-arn=arn:aws:sns:eu-west-1:805248565926:test2 --message "test2:${CIRCLE_WORKFLOW_ID}"

      # docker stuff
      - setup_remote_docker
      - run:
          name: "docker login"
          command: $(aws ecr get-login --no-include-email --region eu-west-1)
      - run:
          name: "docker build"
          command: |
            docker build -t 805248565926.dkr.ecr.eu-west-1.amazonaws.com/foo/fe:test-${CIRCLE_SHA1} .
            docker push 805248565926.dkr.ecr.eu-west-1.amazonaws.com/foo/fe:test-${CIRCLE_SHA1}

    #



# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  testing_things:
    jobs:
      - test
