version: 2
jobs:
    test:
      docker:
        - image: circleci/node:10
      steps:
        - run: ls -lah
        - checkout
        - run: ls -lah
        - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test